<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Anil3151946" name="com.nagp.amazon.tests.AmazonLoginPageTest" tests="5" failures="1" timestamp="2021-05-13T17:31:52 IST" time="45.579" errors="0">
  <testcase name="openLoginScreenTest" time="7.056" classname="com.nagp.amazon.tests.AmazonLoginPageTest"/>
  <system-out/>
  <testcase name="conditionsOfUseTest" time="8.649" classname="com.nagp.amazon.tests.AmazonLoginPageTest"/>
  <system-out/>
  <testcase name="privacyNoticeTest" time="10.581" classname="com.nagp.amazon.tests.AmazonLoginPageTest"/>
  <system-out/>
  <testcase name="loginTest" time="8.751" classname="com.nagp.amazon.tests.AmazonLoginPageTest"/>
  <system-out/>
  <testcase name="failedLoginTest" time="10.542" classname="com.nagp.amazon.tests.AmazonLoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [Your password is incorrect] but found [To better protect your account, please re-enter your password and then enter the characters as they are shown in the image below.]">
      <![CDATA[java.lang.AssertionError: expected [Your password is incorrect] but found [To better protect your account, please re-enter your password and then enter the characters as they are shown in the image below.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.nagp.amazon.tests.AmazonLoginPageTest.failedLoginTest(AmazonLoginPageTest.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- failedLoginTest -->
  <system-out/>
</testsuite> <!-- com.nagp.amazon.tests.AmazonLoginPageTest -->
